version: '2.2'
services:
  logstash:
#    image: docker.elastic.co/logstash/logstash:8.1.3
    image: logstash:8.1.3
    environment:
      - ES_HOST="elasticsearch:9200"
    ports:
      - "5044:5044/udp"
      - "12201:12201/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf

  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    image: elasticsearch:8.1.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
#      - xpack.security.http.ssl.enabled=false
    ports:
      - 9200:9200
    volumes:
      - /tmp/esdata:/tmp/elasticsearch/data

  kibana:
#    image: docker.elastic.co/kibana/kibana:8.1.3
    image: kibana:8.1.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  nginx:
    image: nginx
    ports:
      - "80:80"
#    volumes:
#      - ./nginx:/etc/nginx/conf.d
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
        tag: "nginx"
